### ISSUE TITLE
info

### ISSUE THREAD

**Issue by kulfoon** [easylistpolish/easylistpolish#20]
Just to let you know in case you didn't notice:
https://github.com/uBlockOrigin/uBlock-issues/issues/301
https://github.com/uBlockOrigin/uAssets/issues/4122
https://github.com/NanoAdblocker/NanoCore/issues/229

**Comment by easylistpolish** [comment]
Hey,
thanks for all reports. I added filters for autoline.com.pl, gazetkonosz.pl, livemecz.com, nf.pl and sekrety-zdrowia.org.
For the rest I would need to use more complicated filters. These are having bigger impact on performance so I'm not adding them for just signs "Reklama" or empty space. Too many filters like that could have impact on users, especially with older hardware.
About self-promotion: That's true. Easylists are not blocking this kind of content. ([Ad is the promotion of *third party* content](https://easylist.to/2011/07/11/the-definition-of-advert-and-link-exchange-policy.html))
Best

**Comment by easylistpolish** [comment]
> Good, but for `sekrety-zdrowia.org` and `livemecz.com` still some left

Thanks, I hide it on sekrety-zdrowia.org, but on livemecz.com it's not actually an ad (it's information about place for ad so it doesn't fit in "easylist ad definition") 

> Can you elaborate more (I put the questions it in the spoiler),

Every filter is taking memory space (which is very important especially in mobile devices) and hiding filters is slowing down browser a little bit. There's no big issue with simple filters (like example##.reklama) but more complicated ones have more impact on performance (like example.com##div[class^="rekl"] or example.com#?#div:-abp-contains("reklama") ).
That's why I'm leaving signs like "reklama" or blank spaces in some cases.

**Comment by kulfoon** [comment]
So at least we know (as for the performance impact) that u meant case nr 3 from my spoiler: 
a performance of a single website with a complicated filter/s applied. I generally agree that such kind of extra filters are performance-heavier than typical filters, but every website and filter is different, so the question is: is the performance impact big enought on every particular website to decide to skip blocking the ads? In other words could you show "actual profiling data + analysis supporting the claim" as per https://github.com/ryanbr/fanboy-adblock/issues/655#issuecomment-439336138?

**Comment by easylistpolish** [comment]
I don't have official data but I had cases with bad performance because of too many filters. You can make simple test in development tools in any browser. I.e.
Go to
[https://adblockplus.org/filter-cheatsheet](https://adblockplus.org/filter-cheatsheet)
check network performance
add filters
adblockplus.org#?#code:-abp-contains(http:)
adblockplus.org#?#h3:-abp-contains(Example)
adblockplus.org#?#tr:-abp-has(td:-abp-contains(Include))
check performance again. For me it's more then half second lost because of 3 filters. I have pretty good computer with pretty good internet connection, so you can imagine how big impact it would have on slower devices or mobile in future.

>  is the performance impact big enought on every particular website to decide to skip blocking the ads?
My answer is no. If ad can be block with little impact on performance it's worth to block it. But to block little signs "reklama" or white spaces it's imo not worth it

**Comment by kulfoon** [comment]
> easylistpolish :
> 
> You can make simple test in development tools in any browser. I.e.
> Go to
> https://adblockplus.org/filter-cheatsheet
> check network performance
> add filters
> adblockplus.org#?#code:-abp-contains(http:)
> adblockplus.org#?#h3:-abp-contains(Example)
> adblockplus.org#?#tr:-abp-has(td:-abp-contains(Include))
> check performance again. For me it's more then half second lost because of 3 filters. I have pretty good computer with pretty good internet connection, so you can imagine how big impact it would have on slower devices or mobile in future.

Unable to reproduce, also you haven't provided any numbers/data as a proof, we would like to see the hard numbers. @jspenguin2017 can you reproduce "half second lost"?

**Comment by KonoromiHimaries** [comment]
> Unable to reproduce, in my tests there was completely no loss

can you a prove it?

**Comment by jspenguin2017** [comment]
I see no difference from the profiler when it comes to stylesheet recalculation. 
If you check the time `load` event is fired, then that takes in your Internet connection quality into account as well, which adding filters will not change.

**Comment by kulfoon** [comment]
Too many speculations, no proof, as seen, your performance impact case you've provided was just a speculation without any kind of tech data proof or proper benchmarking, it was a lag / ping / connection dependend and flawed, and now you are sending us again to another such speculation-cases of the user reprots. Therefore, such speculation-cases can not be treated as the arguments to not block some ads on some  webpages.

So your only argument now, is the generic warning on ABP documentation website, and there are two ways of handling such warning:
- a) handle it generic way (no website / case specific) , that's the way you actually do, to avoid using such kind of extra filters at all websites (use them only in very rarely cases), just because of the generic warning on ABP website about the performance impact, which in reality the performance impact is a webpage-case dependend
- b) handle it website / case specific way, add such extra filters to websites if needed, but then do a real case benchmark, to see if they actually cause a performance impact on the webpage (page load slow down) or not (no speculations allowed, only benchmark allowed)

Which way is a more suitable way?  I just know that I don't want to see those annoying and distracting "reclama" words scattered all over the website. But on the other hand, I don't want to enforce the EasyList Polish owner to change the rules. So I'll no more complain, just want to see what other people will say, I'm out as for now.

**Comment by KonoromiHimaries** [comment]
I suggest to make a second list which would contain rules that could affect performance

**Comment by kulfoon** [comment]
Yea, I just have got the same idea (edited my comment) just before your comment had appeared.

**Comment by easylistpolish** [comment]
> Too many speculations, no proof (...) and now you are sending us again to another such speculation-cases of the user reprots.

I was saying from the begining that I don't have official data and you kept asking me.
 
> So your only argument now, is the generic warning on ABP documentation website, 

Yes, except of my experience, that's my only argument. When I see in documentation "don't do that" and my experience is showing me they are right then I'm not looking for a proof. If you want, you can make some case study and make test on different devices (also mobile) to check impact of too long easylist with to many complicated filters. It's not my duty to take my time to give you a proof (I'm not software tester so "my time" include to learn how to do everything properly, including Android, iOS etc.).

>and there are two ways of handling such warning:
> 
>     * a) handle it generic way (no website / case specific) , that's the way you actually do, to avoid using such kind of extra filters at all websites (use them only in very rarely cases), just because of the generic warning on ABP website about the performance impact, which in reality the performance impact is a webpage-case dependend

You can't make general extended hiding filters in ABP because it would have impact on performance on every page and would be very risky (could cause a lot of false positive issues). 
Even if you would like to add general regular filters just to block sign it's too risky. Eg filter ##.Reklama (from your list) could block a field about advertising offer from a page. And as you know easylists doesn't want to block any content which is not an ad.

>     * b) handle it website / case specific way, add such extra filters to websites if needed, but then do a real case benchmark, to see if they actually cause a performance impact on the webpage (page load slow down) or not (no speculations allowed, only benchmark allowed)

If you have time to make a benchmark for every case on different devices with different hardware and regularly check for changes on these pages then sure. Unfortunately I don't have equipment, knowledge, time and anybody else to do that. 
Luckily I have reports, so if something is annoying for users, I can see a scale of a problem. There was almost no complaining about "reklama" signs issue.

> EDITED: OK I've got an idea, perhaps to create a supplement list to EasyList Polish to handle such ads "reclama" words and things which require extra filters? This way people who want to remove them will enable the supplement, and people who have performance problems or old hardware will not use it.

That's a good idea. There could be an extra list for "heavier" filters to get rid off "reklama" signs and empty fields.

**Comment by kulfoon** [comment]
Hey, so as for the unfixed websites:
https://github.com/NanoAdblocker/NanoCore/issues/229#issuecomment-448217773 and
https://github.com/NanoAdblocker/NanoCore/issues/229#issuecomment-449431313
Are you going to create the discussed small supplement list for EasyList Polish to fix the above issues.

**Comment by easylistpolish** [comment]
I see that somebody else started to do it

**Comment by kulfoon** [comment]
> jspenguin2017: https://github.com/NanoAdblocker/NanoCore/issues/229#issuecomment-468870535

> jspenguin2017: As I said, I will not add EasyList Polish to assets.json

You misunderstood and locking threads before I can reply and correct it is ulgy, because it makes me looks like a fool, wherein not me was the fool here. I nowhere said I want EasyList Polish to be added to Nano, there was nothing of such a thing in my comment, I was just showing some statisctics of how many placeholder issues are fixed or declined by EasyList Polish and thus need to be fixed in Nano placeholder list, to show that existing of Nano placeholder list does make sense.

**Comment by jspenguin2017** [comment]
@kulfoon Since EasyList Polish is not in the default filters manifest, I would like to have the fixes accepted by EasyList Polish to be in the placeholder buster filter as well. There is no point in showing statistics anymore at this point, just send them all to placeholder buster, fixed by EasyList Polish or not.
